package ctas.test.entity;

import java.util.Date;

public class Dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_dictionary.id
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_dictionary.parent_code
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_dictionary.code
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_dictionary.name
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_dictionary.is_delete
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_dictionary.create_user
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_dictionary.create_time
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_dictionary.id
     *
     * @return the value of mbk_dictionary.id
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_dictionary.id
     *
     * @param id the value for mbk_dictionary.id
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_dictionary.parent_code
     *
     * @return the value of mbk_dictionary.parent_code
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_dictionary.parent_code
     *
     * @param parentCode the value for mbk_dictionary.parent_code
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_dictionary.code
     *
     * @return the value of mbk_dictionary.code
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_dictionary.code
     *
     * @param code the value for mbk_dictionary.code
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_dictionary.name
     *
     * @return the value of mbk_dictionary.name
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_dictionary.name
     *
     * @param name the value for mbk_dictionary.name
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_dictionary.is_delete
     *
     * @return the value of mbk_dictionary.is_delete
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_dictionary.is_delete
     *
     * @param isDelete the value for mbk_dictionary.is_delete
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_dictionary.create_user
     *
     * @return the value of mbk_dictionary.create_user
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_dictionary.create_user
     *
     * @param createUser the value for mbk_dictionary.create_user
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_dictionary.create_time
     *
     * @return the value of mbk_dictionary.create_time
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_dictionary.create_time
     *
     * @param createTime the value for mbk_dictionary.create_time
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}