package ctas.test.entity;

import java.util.Date;

public class HardwareDevelopmentApproveLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development_ approve_log.id
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development_ approve_log.hd_id
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Integer hdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development_ approve_log.point
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development_ approve_log.result
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development_ approve_log.create_user
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development_ approve_log.create_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development_ approve_log.remark
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development_ approve_log.id
     *
     * @return the value of mbk_hardware_development_ approve_log.id
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development_ approve_log.id
     *
     * @param id the value for mbk_hardware_development_ approve_log.id
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development_ approve_log.hd_id
     *
     * @return the value of mbk_hardware_development_ approve_log.hd_id
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Integer getHdId() {
        return hdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development_ approve_log.hd_id
     *
     * @param hdId the value for mbk_hardware_development_ approve_log.hd_id
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setHdId(Integer hdId) {
        this.hdId = hdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development_ approve_log.point
     *
     * @return the value of mbk_hardware_development_ approve_log.point
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development_ approve_log.point
     *
     * @param point the value for mbk_hardware_development_ approve_log.point
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setPoint(String point) {
        this.point = point == null ? null : point.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development_ approve_log.result
     *
     * @return the value of mbk_hardware_development_ approve_log.result
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development_ approve_log.result
     *
     * @param result the value for mbk_hardware_development_ approve_log.result
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development_ approve_log.create_user
     *
     * @return the value of mbk_hardware_development_ approve_log.create_user
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development_ approve_log.create_user
     *
     * @param createUser the value for mbk_hardware_development_ approve_log.create_user
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development_ approve_log.create_time
     *
     * @return the value of mbk_hardware_development_ approve_log.create_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development_ approve_log.create_time
     *
     * @param createTime the value for mbk_hardware_development_ approve_log.create_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development_ approve_log.remark
     *
     * @return the value of mbk_hardware_development_ approve_log.remark
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development_ approve_log.remark
     *
     * @param remark the value for mbk_hardware_development_ approve_log.remark
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}