package ctas.test.entity;

import java.util.Date;

public class HardwareDevelopment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.id
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.apply_no
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.apply_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String applyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.status
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.legal_person_company
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String legalPersonCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.product_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.product_name
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.product_no_change
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String productNoChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.product_no_change_after
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String productNoChangeAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.product_arrive_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Date productArriveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.product_number
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Integer productNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.product_change_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String productChangeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.import_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String importType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.import_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String importDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.timing_import_date
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Date timingImportDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.cost_affect
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String costAffect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.deadline_affect
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String deadlineAffect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.project_affect
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String projectAffect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.detailed_requirement_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String detailedRequirementDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.change_reason
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String changeReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.change_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String changeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.change_type_other_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String changeTypeOtherDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.change_purview
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String changePurview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.change_purview_other_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String changePurviewOtherDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.involve_department
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String involveDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.involve_department_other_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String involveDepartmentOtherDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.change_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String changeDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.change_describe_after
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String changeDescribeAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.commit_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Date commitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.create_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.create_user
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.create_user_mis
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String createUserMis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.update_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.update_user
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbk_hardware_development.remark
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.id
     *
     * @return the value of mbk_hardware_development.id
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.id
     *
     * @param id the value for mbk_hardware_development.id
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.apply_no
     *
     * @return the value of mbk_hardware_development.apply_no
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.apply_no
     *
     * @param applyNo the value for mbk_hardware_development.apply_no
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo == null ? null : applyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.apply_type
     *
     * @return the value of mbk_hardware_development.apply_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.apply_type
     *
     * @param applyType the value for mbk_hardware_development.apply_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setApplyType(String applyType) {
        this.applyType = applyType == null ? null : applyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.status
     *
     * @return the value of mbk_hardware_development.status
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.status
     *
     * @param status the value for mbk_hardware_development.status
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.legal_person_company
     *
     * @return the value of mbk_hardware_development.legal_person_company
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getLegalPersonCompany() {
        return legalPersonCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.legal_person_company
     *
     * @param legalPersonCompany the value for mbk_hardware_development.legal_person_company
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setLegalPersonCompany(String legalPersonCompany) {
        this.legalPersonCompany = legalPersonCompany == null ? null : legalPersonCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.product_type
     *
     * @return the value of mbk_hardware_development.product_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.product_type
     *
     * @param productType the value for mbk_hardware_development.product_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.product_name
     *
     * @return the value of mbk_hardware_development.product_name
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.product_name
     *
     * @param productName the value for mbk_hardware_development.product_name
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.product_no_change
     *
     * @return the value of mbk_hardware_development.product_no_change
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getProductNoChange() {
        return productNoChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.product_no_change
     *
     * @param productNoChange the value for mbk_hardware_development.product_no_change
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setProductNoChange(String productNoChange) {
        this.productNoChange = productNoChange == null ? null : productNoChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.product_no_change_after
     *
     * @return the value of mbk_hardware_development.product_no_change_after
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getProductNoChangeAfter() {
        return productNoChangeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.product_no_change_after
     *
     * @param productNoChangeAfter the value for mbk_hardware_development.product_no_change_after
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setProductNoChangeAfter(String productNoChangeAfter) {
        this.productNoChangeAfter = productNoChangeAfter == null ? null : productNoChangeAfter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.product_arrive_time
     *
     * @return the value of mbk_hardware_development.product_arrive_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Date getProductArriveTime() {
        return productArriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.product_arrive_time
     *
     * @param productArriveTime the value for mbk_hardware_development.product_arrive_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setProductArriveTime(Date productArriveTime) {
        this.productArriveTime = productArriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.product_number
     *
     * @return the value of mbk_hardware_development.product_number
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.product_number
     *
     * @param productNumber the value for mbk_hardware_development.product_number
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.product_change_type
     *
     * @return the value of mbk_hardware_development.product_change_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getProductChangeType() {
        return productChangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.product_change_type
     *
     * @param productChangeType the value for mbk_hardware_development.product_change_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setProductChangeType(String productChangeType) {
        this.productChangeType = productChangeType == null ? null : productChangeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.import_type
     *
     * @return the value of mbk_hardware_development.import_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getImportType() {
        return importType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.import_type
     *
     * @param importType the value for mbk_hardware_development.import_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setImportType(String importType) {
        this.importType = importType == null ? null : importType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.import_describe
     *
     * @return the value of mbk_hardware_development.import_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getImportDescribe() {
        return importDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.import_describe
     *
     * @param importDescribe the value for mbk_hardware_development.import_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setImportDescribe(String importDescribe) {
        this.importDescribe = importDescribe == null ? null : importDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.timing_import_date
     *
     * @return the value of mbk_hardware_development.timing_import_date
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Date getTimingImportDate() {
        return timingImportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.timing_import_date
     *
     * @param timingImportDate the value for mbk_hardware_development.timing_import_date
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setTimingImportDate(Date timingImportDate) {
        this.timingImportDate = timingImportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.cost_affect
     *
     * @return the value of mbk_hardware_development.cost_affect
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getCostAffect() {
        return costAffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.cost_affect
     *
     * @param costAffect the value for mbk_hardware_development.cost_affect
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setCostAffect(String costAffect) {
        this.costAffect = costAffect == null ? null : costAffect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.deadline_affect
     *
     * @return the value of mbk_hardware_development.deadline_affect
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getDeadlineAffect() {
        return deadlineAffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.deadline_affect
     *
     * @param deadlineAffect the value for mbk_hardware_development.deadline_affect
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setDeadlineAffect(String deadlineAffect) {
        this.deadlineAffect = deadlineAffect == null ? null : deadlineAffect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.project_affect
     *
     * @return the value of mbk_hardware_development.project_affect
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getProjectAffect() {
        return projectAffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.project_affect
     *
     * @param projectAffect the value for mbk_hardware_development.project_affect
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setProjectAffect(String projectAffect) {
        this.projectAffect = projectAffect == null ? null : projectAffect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.detailed_requirement_describe
     *
     * @return the value of mbk_hardware_development.detailed_requirement_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getDetailedRequirementDescribe() {
        return detailedRequirementDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.detailed_requirement_describe
     *
     * @param detailedRequirementDescribe the value for mbk_hardware_development.detailed_requirement_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setDetailedRequirementDescribe(String detailedRequirementDescribe) {
        this.detailedRequirementDescribe = detailedRequirementDescribe == null ? null : detailedRequirementDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.change_reason
     *
     * @return the value of mbk_hardware_development.change_reason
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getChangeReason() {
        return changeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.change_reason
     *
     * @param changeReason the value for mbk_hardware_development.change_reason
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setChangeReason(String changeReason) {
        this.changeReason = changeReason == null ? null : changeReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.change_type
     *
     * @return the value of mbk_hardware_development.change_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.change_type
     *
     * @param changeType the value for mbk_hardware_development.change_type
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setChangeType(String changeType) {
        this.changeType = changeType == null ? null : changeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.change_type_other_describe
     *
     * @return the value of mbk_hardware_development.change_type_other_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getChangeTypeOtherDescribe() {
        return changeTypeOtherDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.change_type_other_describe
     *
     * @param changeTypeOtherDescribe the value for mbk_hardware_development.change_type_other_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setChangeTypeOtherDescribe(String changeTypeOtherDescribe) {
        this.changeTypeOtherDescribe = changeTypeOtherDescribe == null ? null : changeTypeOtherDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.change_purview
     *
     * @return the value of mbk_hardware_development.change_purview
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getChangePurview() {
        return changePurview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.change_purview
     *
     * @param changePurview the value for mbk_hardware_development.change_purview
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setChangePurview(String changePurview) {
        this.changePurview = changePurview == null ? null : changePurview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.change_purview_other_describe
     *
     * @return the value of mbk_hardware_development.change_purview_other_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getChangePurviewOtherDescribe() {
        return changePurviewOtherDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.change_purview_other_describe
     *
     * @param changePurviewOtherDescribe the value for mbk_hardware_development.change_purview_other_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setChangePurviewOtherDescribe(String changePurviewOtherDescribe) {
        this.changePurviewOtherDescribe = changePurviewOtherDescribe == null ? null : changePurviewOtherDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.involve_department
     *
     * @return the value of mbk_hardware_development.involve_department
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getInvolveDepartment() {
        return involveDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.involve_department
     *
     * @param involveDepartment the value for mbk_hardware_development.involve_department
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setInvolveDepartment(String involveDepartment) {
        this.involveDepartment = involveDepartment == null ? null : involveDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.involve_department_other_describe
     *
     * @return the value of mbk_hardware_development.involve_department_other_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getInvolveDepartmentOtherDescribe() {
        return involveDepartmentOtherDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.involve_department_other_describe
     *
     * @param involveDepartmentOtherDescribe the value for mbk_hardware_development.involve_department_other_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setInvolveDepartmentOtherDescribe(String involveDepartmentOtherDescribe) {
        this.involveDepartmentOtherDescribe = involveDepartmentOtherDescribe == null ? null : involveDepartmentOtherDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.change_describe
     *
     * @return the value of mbk_hardware_development.change_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getChangeDescribe() {
        return changeDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.change_describe
     *
     * @param changeDescribe the value for mbk_hardware_development.change_describe
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setChangeDescribe(String changeDescribe) {
        this.changeDescribe = changeDescribe == null ? null : changeDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.change_describe_after
     *
     * @return the value of mbk_hardware_development.change_describe_after
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getChangeDescribeAfter() {
        return changeDescribeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.change_describe_after
     *
     * @param changeDescribeAfter the value for mbk_hardware_development.change_describe_after
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setChangeDescribeAfter(String changeDescribeAfter) {
        this.changeDescribeAfter = changeDescribeAfter == null ? null : changeDescribeAfter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.commit_time
     *
     * @return the value of mbk_hardware_development.commit_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Date getCommitTime() {
        return commitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.commit_time
     *
     * @param commitTime the value for mbk_hardware_development.commit_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.create_time
     *
     * @return the value of mbk_hardware_development.create_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.create_time
     *
     * @param createTime the value for mbk_hardware_development.create_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.create_user
     *
     * @return the value of mbk_hardware_development.create_user
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.create_user
     *
     * @param createUser the value for mbk_hardware_development.create_user
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.create_user_mis
     *
     * @return the value of mbk_hardware_development.create_user_mis
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getCreateUserMis() {
        return createUserMis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.create_user_mis
     *
     * @param createUserMis the value for mbk_hardware_development.create_user_mis
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setCreateUserMis(String createUserMis) {
        this.createUserMis = createUserMis == null ? null : createUserMis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.update_time
     *
     * @return the value of mbk_hardware_development.update_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.update_time
     *
     * @param updateTime the value for mbk_hardware_development.update_time
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.update_user
     *
     * @return the value of mbk_hardware_development.update_user
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.update_user
     *
     * @param updateUser the value for mbk_hardware_development.update_user
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbk_hardware_development.remark
     *
     * @return the value of mbk_hardware_development.remark
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbk_hardware_development.remark
     *
     * @param remark the value for mbk_hardware_development.remark
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}