package ctas.test.mapper;

import ctas.test.entity.Dictionary;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_dictionary
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_dictionary
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_dictionary
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    int insertSelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_dictionary
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    Dictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_dictionary
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_dictionary
     *
     * @mbggenerated Fri Feb 28 16:05:09 CST 2020
     */
    int updateByPrimaryKey(Dictionary record);
}