package ctas.test.mapper;

import ctas.test.entity.HardwareDevelopmentApproveLog;

public interface HardwareDevelopmentApproveLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development_ approve_log
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development_ approve_log
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    int insert(HardwareDevelopmentApproveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development_ approve_log
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    int insertSelective(HardwareDevelopmentApproveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development_ approve_log
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    HardwareDevelopmentApproveLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development_ approve_log
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    int updateByPrimaryKeySelective(HardwareDevelopmentApproveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development_ approve_log
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    int updateByPrimaryKey(HardwareDevelopmentApproveLog record);
}