package ctas.test.mapper;

import ctas.test.entity.HardwareDevelopment;

public interface HardwareDevelopmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    int insert(HardwareDevelopment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    int insertSelective(HardwareDevelopment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    HardwareDevelopment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    int updateByPrimaryKeySelective(HardwareDevelopment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mbk_hardware_development
     *
     * @mbggenerated Fri Feb 28 10:25:56 CST 2020
     */
    int updateByPrimaryKey(HardwareDevelopment record);
}